### PR TITLE
Link to pyosmium-up-to-date

### PR DESCRIPTION
**Pull request by wipfli**
Adds a link to pyosmium-up-to-date to patch the latest OpenStreetMap edits onto an existing planet.osm.pbf file.

### CODE REVIEW

**Comment by msbarry** [comment]
@wipfli I think you need to run `mvn spotless:apply` on this first

**Comment by wipfli** [comment]
Hm, I am so bad with java.

```
➜  planetiler git:(patch-2) ✗ mvn spotless:apply                         
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
```

**Comment by wipfli** [comment]
And
```
➜  planetiler git:(patch-2) ✗ ./mvnw spotless:apply
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/wipfli/maps/planetiler/planetiler-openmaptiles/submodule.pom.xml of /home/wipfli/maps/planetiler/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.onthegomap.planetiler:planetiler-parent:0.6-SNAPSHOT (/home/wipfli/maps/planetiler/pom.xml) has 1 error
[ERROR]     Child module /home/wipfli/maps/planetiler/planetiler-openmaptiles/submodule.pom.xml of /home/wipfli/maps/planetiler/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by msbarry** [comment]
> Hm, I am so bad with java.

no problem I got it

**Pull request merged**
